module.exports = [
  {
    "id": "a4d77a33-6345-452f-a56d-1519a765ce7d",
    "title": "Embrace Of Souls",
    "slug": "embrace-of-souls-1",
    "imageUrl": "/images/gallery/gallery_1.jpg",
    "thumbnailUrl": "/images/gallery/gallery_1.jpg",
    "originalUrl": "https://i.ibb.co/qYn6VSwq/IMG-20260522-181511.png",
    "category": "Painting",
    "description": "This is a contemporary abstract portrait that celebrates the beauty of connection, individuality, and unspoken emotions. The overlapping faces symbolize unity despite different identities, while their calm expressions reflect peace, trust, and inner strength. Rich floral elements represent growth, love, and resilience, adding a gentle contrast to the bold geometric composition. The vibrant crimson background radiates warmth, passion, and life, making the artwork a striking focal point in any interior.\n\nThis painting invites viewers to interpret their own story, making it a timeless piece that resonates differently with everyone who experiences it.\nPerfect For: Modern homes, luxury interiors, offices, art galleries, hotels, cafés, and collectors of contemporary art.\nMedium: Acrylic on Canvas\nSize: 3 × 4 feet (36 × 48 inches)",
    "year": "2026",
    "sortOrder": 1,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.914Z",
    "updatedAt": "2026-08-19T11:35:27.915Z"
  },
  {
    "id": "2b96959c-cf8a-4968-b3fb-a6c3577efa57",
    "title": "Lord Shiva – Graphite Pencil Art",
    "slug": "lord-shiva-graphite-pencil-art-2",
    "imageUrl": "/images/gallery/gallery_2.jpg",
    "thumbnailUrl": "/images/gallery/gallery_2.jpg",
    "originalUrl": "https://i.ibb.co/twk3Jbtr/IMG-20260215-105349.jpg",
    "category": "Pencil Portraits",
    "description": "This artwork is a detailed graphite pencil drawing of Lord Shiva. The drawing shows his calm and peaceful face, expressing deep emotion and inner strength. I have carefully used light and dark shading to create depth and realism. Every detail, from his hair to his facial features, is drawn with patience and precision. The soft pencil strokes give the portrait a natural appearance. Lord Shiva is often known as the destroyer of evil and the symbol of transformation and new beginnings. In this artwork, his peaceful expression represents balance, wisdom, and spiritual power. This piece is perfect for people who appreciate spiritual art and traditional pencil drawings. It reflects devotion, creativity, and respect for Indian culture. \nmedium :graphite pencil on paper\ncategory :original artwork",
    "year": "2026",
    "sortOrder": 2,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.915Z",
    "updatedAt": "2026-08-19T11:35:27.915Z"
  },
  {
    "id": "5082d7e2-54d1-49c3-b4dd-8b8182c161a9",
    "title": "Kaantha Movie Poster",
    "slug": "kaantha-movie-poster-3",
    "imageUrl": "/images/gallery/gallery_3.jpg",
    "thumbnailUrl": "/images/gallery/gallery_3.jpg",
    "originalUrl": "https://i.ibb.co/spHBGs2v/IMG-20251226-122215.jpg",
    "category": "Pencil Portraits",
    "description": "Kaantha Movie Poster Drawing This artwork is a hand-drawn poster illustration for the movie Kaantha, featuring Rana Daggubati, Dulquer Salmaan, Bhagya Sri, and Samuthirakani portrayed in a single composition inspired by the official movie poster. The drawing includes the movie title Kaantha as part of the artwork, keeping the design clean and true to the original promotional style. This piece was created and presented during a movie promotion event held at my college.After viewing the drawing, the actors appreciated the work, and I received their autographs. Notably, Rana Daggubati personally asked to sign the artwork, making it a memorable and rewarding recognition of the effort and skill involved. The artwork reflects skill in portrait rendering, poster layout, and visual storytelling for film promotion. Artwork Type: Movie poster illustration Style: pencil art(Steadler pencils on Ivory paper)",
    "year": "2025",
    "sortOrder": 3,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.916Z",
    "updatedAt": "2026-08-19T11:35:27.916Z"
  },
  {
    "id": "215d8770-3876-4efc-926b-f2aae98c08f9",
    "title": "Blood art",
    "slug": "blood-art-4",
    "imageUrl": "/images/gallery/gallery_4.jpg",
    "thumbnailUrl": "/images/gallery/gallery_4.jpg",
    "originalUrl": "https://i.ibb.co/d0gQmgTX/IMG-20251226-122559.jpg",
    "category": "Painting",
    "description": "Commissioned Portrait Artwork This is a commissioned portrait artwork of a girl, created with a unique and unconventional artistic approach. The artwork focuses on capturing emotion, expression, and depth through careful detailing and controlled tonal variation. Designed according to the client’s vision, this piece reflects artistic experimentation, precision, and strong emotional impact. It stands out as a distinctive portrait that blends creativity with meaningful expression. Artwork Type: Commissioned portrait Medium : Blood art",
    "year": "2025",
    "sortOrder": 4,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.916Z",
    "updatedAt": "2026-08-19T11:35:27.916Z"
  },
  {
    "id": "42a8c982-3267-433c-a466-5c059b1fb07e",
    "title": "Gautama Buddha",
    "slug": "gautama-buddha-5",
    "imageUrl": "/images/gallery/gallery_5.jpg",
    "thumbnailUrl": "/images/gallery/gallery_5.jpg",
    "originalUrl": "https://i.ibb.co/pBs1QDsz/IMG-20251226-122910.jpg",
    "category": "Painting",
    "description": "Lord Buddha Painting This painting of Lord Buddha presents a calm and meditative presence through balanced composition and gentle visual elements. Thoughtful use of form and tone highlights serenity, wisdom, and inner peace. The artwork creates a soothing atmosphere, making it suitable for meditation spaces, homes, offices, or wellness interiors. It reflects mindfulness and spiritual harmony in a refined artistic form. Artwork Type: Hand-painted original artwork(acrylic painting on canvas)",
    "year": "2025",
    "sortOrder": 5,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "e56b1cee-c0e9-499c-8ce3-fa57e8a04e73",
    "title": "Unique Commission Work",
    "slug": "unique-commission-work-6",
    "imageUrl": "/images/gallery/gallery_6.jpg",
    "thumbnailUrl": "/images/gallery/gallery_6.jpg",
    "originalUrl": "https://i.ibb.co/w57N5qd/IMG-20260101-091333.jpg",
    "category": "Pencil Portraits",
    "description": "Combined Pencil Portrait (Commissioned Artwork)\n\nThis commissioned pencil drawing is created by carefully combining two separate reference images into a single composition,the person portrayed alongside celebrity Pawan Kalyan . Precise observation and refined pencil technique are used to maintain accuracy in features, proportions, and overall harmony between both subjects.\n\nThe artwork reflects thoughtful planning and precision, transforming individual photographs into one portrait. Created as a custom order, this piece serves as a meaningful and personalized artwork.\n\nMedium: Pencil on paper\nArtwork Type: Commissioned portrait\nSpecial Detail: Two separate images combined into one drawing",
    "year": "2024",
    "sortOrder": 6,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "bd21081f-6a72-458b-b1bb-56a358fae476",
    "title": "Blood art",
    "slug": "blood-art-7",
    "imageUrl": "/images/gallery/gallery_7.jpg",
    "thumbnailUrl": "/images/gallery/gallery_7.jpg",
    "originalUrl": "https://i.ibb.co/Z6xqNHCP/IMG-20260101-090850.jpg",
    "category": "Painting",
    "description": "Commissioned Blood Art Portrait – Santhoshi Gopala Krishnan\n\nThis artwork is a commissioned blood art portrait of Santhoshi Gopala Krishnan, a renowned makeup expert and entrepreneur with a strong public presence and over 1 million followers. The portrait focuses on expression, structure, and depth, using the medium in a symbolic and artistic manner.\n\nCreated as a custom order, this piece reflects experimental creativity, precision, and thoughtful execution. It stands as a distinctive portrait honoring a widely recognized personality in the beauty and fashion industry.\n\nMedium: Blood on paper\nArtwork Type: Commissioned portrait",
    "year": "2025",
    "sortOrder": 7,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "dee38c0e-f6af-4b60-bed8-53207ef50426",
    "title": "Caricature Art",
    "slug": "caricature-art-8",
    "imageUrl": "/images/gallery/gallery_8.jpg",
    "thumbnailUrl": "/images/gallery/gallery_8.jpg",
    "originalUrl": "https://i.ibb.co/1trH06jk/IMG-20260101-085225.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 8,
    "isFeatured": true,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "756b7bc2-68f9-43e2-b852-1010b8677f2e",
    "title": "Pencil Portrait Commission work",
    "slug": "pencil-portrait-commission-work-9",
    "imageUrl": "/images/gallery/gallery_9.jpg",
    "thumbnailUrl": "/images/gallery/gallery_9.jpg",
    "originalUrl": "https://i.ibb.co/XxK8w0PD/IMG-20260101-090705.jpg",
    "category": "Pencil Portraits",
    "description": " Pencil Portrait – Traditional Attire\n\nThis commissioned pencil portrait depicts a girl in a saree, adorned with traditional jewellery, rendered with precise line work and controlled shading. Attention is given to facial structure, fabric folds, and ornamental details to achieve clarity and realism.\n\nThe artwork is created based on client reference and executed with a refined approach, resulting in a dignified and timeless portrait.\n\nMedium: Pencil on paper( Steadleer pencils on Ivory paper)\nCategory: Commissioned portrait artwork",
    "year": "2025",
    "sortOrder": 9,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "ba458576-39cd-4df8-a65e-3c7aaa619421",
    "title": "Commission Work",
    "slug": "commission-work-10",
    "imageUrl": "/images/gallery/gallery_10.jpg",
    "thumbnailUrl": "/images/gallery/gallery_10.jpg",
    "originalUrl": "https://i.ibb.co/BVZn60Lz/IMG-20260101-091233.jpg",
    "category": "Pencil Portraits",
    "description": "Couple Graphite Pencil Portrait \n\nA custom graphite pencil portrait of a couple, drawn with fine detailing and smooth shading to capture likeness and emotion.\nThis commissioned artwork is carefully created based on reference photos, making it a meaningful and timeless keepsake.\n\nMedium: Graphite pencil on paper(Artline pencils on Ivory paper)\nArtwork Type: Commissioned portrait",
    "year": "2024",
    "sortOrder": 10,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "57773cca-e451-4dbf-aae8-2acccec32e2c",
    "title": "Live Caricature",
    "slug": "live-caricature-11",
    "imageUrl": "/images/gallery/gallery_11.jpg",
    "thumbnailUrl": "/images/gallery/gallery_11.jpg",
    "originalUrl": "https://i.ibb.co/3yS65jFQ/IMG-20260101-084445.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 11,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "a586c752-c6b9-45cf-8c89-3c41017c377e",
    "title": "Live Caricature",
    "slug": "live-caricature-12",
    "imageUrl": "/images/gallery/gallery_12.jpg",
    "thumbnailUrl": "/images/gallery/gallery_12.jpg",
    "originalUrl": "https://i.ibb.co/F4hJcWv5/IMG-20260101-085311.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2026",
    "sortOrder": 12,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:27.917Z",
    "updatedAt": "2026-08-19T11:35:27.917Z"
  },
  {
    "id": "d478ed5f-46d8-4ece-9570-da374420e918",
    "title": "Live Caricature",
    "slug": "live-caricature-13",
    "imageUrl": "/images/gallery/gallery_13.jpg",
    "thumbnailUrl": "/images/gallery/gallery_13.jpg",
    "originalUrl": "https://i.ibb.co/PZg8f9G2/IMG-20251226-123003.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 13,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.077Z",
    "updatedAt": "2026-08-19T11:35:30.077Z"
  },
  {
    "id": "95a476ff-2d0c-4c6d-96e8-9f7c24f110d2",
    "title": "Radha Krishna",
    "slug": "radha-krishna-14",
    "imageUrl": "/images/gallery/gallery_14.jpg",
    "thumbnailUrl": "/images/gallery/gallery_14.jpg",
    "originalUrl": "https://i.ibb.co/zH2dDx9d/IMG-20251226-121236.jpg",
    "category": "Pencil Portraits",
    "description": "Radha Krishna Colour Pencil Drawing\n\nThis colour pencil drawing of Radha and Krishna portrays their divine connection through expressive detailing and harmonious colour tones. Careful layering and smooth blending give depth to their features, attire, and graceful posture.\n\nThe artwork reflects love, devotion, and spiritual balance, creating a calm and uplifting visual experience. It is a timeless piece suited for sacred spaces, art displays, or personal collections.\n\nMedium: Colour pencil on paper\nType: Hand-drawn original artwork",
    "year": "2021",
    "sortOrder": 14,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "d2aa9cbf-5b4b-44e6-b5cd-36be4b582dba",
    "title": "Sita Ram",
    "slug": "sita-ram-15",
    "imageUrl": "/images/gallery/gallery_15.jpg",
    "thumbnailUrl": "/images/gallery/gallery_15.jpg",
    "originalUrl": "https://i.ibb.co/vxj6JWmG/IMG-20250926-095042.jpg",
    "category": "Painting",
    "description": "Sita Ram Watercolour Painting\n\nThis watercolour painting of Sita and Ram is created on paper using soft, flowing colours that give the artwork a gentle and devotional feel. Subtle brushwork and balanced tones highlight their calm expressions and divine presence.\n\nThe painting reflects values of love, devotion, and harmony, making it a peaceful and meaningful piece of art. It is well suited for home décor, prayer rooms, or spiritual collections.\n\nMedium: Watercolour on paper(camlin watercolours)\nType: Hand-painted original artwork",
    "year": "2024",
    "sortOrder": 15,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "9c5a8a71-d4fd-4332-91ee-f02b21878995",
    "title": "Commission Work",
    "slug": "commission-work-16",
    "imageUrl": "/images/gallery/gallery_16.jpg",
    "thumbnailUrl": "/images/gallery/gallery_16.jpg",
    "originalUrl": "https://i.ibb.co/0V9xJLg3/IMG-20251226-114306.jpg",
    "category": "Pencil Portraits",
    "description": "Lord Shiva and Ravana Pencil Artwork (Commissioned). This hand-drawn pencil artwork depicts the divine bond between Lord Shiva and Ravana, highlighting reverence, devotion, and spiritual connection. The intricate pencil work captures detailed expressions, gestures, and symbolic elements, reflecting both the intensity and respect in their relationship. This piece was commissioned by a devotee of Ravana, showcasing the deep admiration and faith behind the creation. The artwork balances realism with devotion, making it a meaningful and unique portrayal of this mythological relationship.\n Medium: Pencil on paper(Steadler pencils and Ivory Paper) Type: Commissioned artwork",
    "year": "2025",
    "sortOrder": 16,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "35cad36d-3844-4a0b-a7fd-b42ebbf621ad",
    "title": "Live Caricature",
    "slug": "live-caricature-17",
    "imageUrl": "/images/gallery/gallery_17.jpg",
    "thumbnailUrl": "/images/gallery/gallery_17.jpg",
    "originalUrl": "https://i.ibb.co/wNPQvtxW/IMG-20250925-163844.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 17,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "60c7462d-86fc-4192-9df7-db437ee9d570",
    "title": "Live Caricature",
    "slug": "live-caricature-18",
    "imageUrl": "/images/gallery/gallery_18.jpg",
    "thumbnailUrl": "/images/gallery/gallery_18.jpg",
    "originalUrl": "https://i.ibb.co/6ck7xYp3/IMG-20251027-WA0013.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 18,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "d487ab0d-ac87-46fd-bc7c-3c29b4ebde3a",
    "title": "Live Caricature",
    "slug": "live-caricature-19",
    "imageUrl": "/images/gallery/gallery_19.jpg",
    "thumbnailUrl": "/images/gallery/gallery_19.jpg",
    "originalUrl": "https://i.ibb.co/2YqRWGCZ/IMG-20251031-235844.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 19,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "1cbb2527-4f6e-4e59-a7b9-d328cfd749f1",
    "title": "Live Caricature",
    "slug": "live-caricature-20",
    "imageUrl": "/images/gallery/gallery_20.jpg",
    "thumbnailUrl": "/images/gallery/gallery_20.jpg",
    "originalUrl": "https://i.ibb.co/jZwfTFrB/IMG-20251226-112625.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 20,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.078Z",
    "updatedAt": "2026-08-19T11:35:30.078Z"
  },
  {
    "id": "fdecd868-9682-4c32-8358-d5f740f27e93",
    "title": "Live Caricature",
    "slug": "live-caricature-21",
    "imageUrl": "/images/gallery/gallery_21.jpg",
    "thumbnailUrl": "/images/gallery/gallery_21.jpg",
    "originalUrl": "https://i.ibb.co/WWTz7sFj/IMG-20251226-112653.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 21,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.508Z",
    "updatedAt": "2026-08-19T11:35:30.508Z"
  },
  {
    "id": "9bdd7ec5-f57c-465a-8191-fcb74931c982",
    "title": "Live Caricature",
    "slug": "live-caricature-22",
    "imageUrl": "/images/gallery/gallery_22.jpg",
    "thumbnailUrl": "/images/gallery/gallery_22.jpg",
    "originalUrl": "https://i.ibb.co/5Wfyw42n/IMG-20251226-112935.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 22,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:30.765Z",
    "updatedAt": "2026-08-19T11:35:30.766Z"
  },
  {
    "id": "299653b8-4587-4596-ab4b-a2467ff0f055",
    "title": "Live Caricature",
    "slug": "live-caricature-23",
    "imageUrl": "/images/gallery/gallery_23.jpg",
    "thumbnailUrl": "/images/gallery/gallery_23.jpg",
    "originalUrl": "https://i.ibb.co/HfzHQZNY/IMG-20251226-111837.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 23,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:31.070Z",
    "updatedAt": "2026-08-19T11:35:31.070Z"
  },
  {
    "id": "27081aa1-749d-4260-83c2-36a739089289",
    "title": "Live Caricature",
    "slug": "live-caricature-24",
    "imageUrl": "/images/gallery/gallery_24.jpg",
    "thumbnailUrl": "/images/gallery/gallery_24.jpg",
    "originalUrl": "https://i.ibb.co/5gz1DYWX/IMG-20251226-111823.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 24,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:31.286Z",
    "updatedAt": "2026-08-19T11:35:31.286Z"
  },
  {
    "id": "6a12b757-1043-4429-886f-6d1fed3ab557",
    "title": "Live Caricature",
    "slug": "live-caricature-25",
    "imageUrl": "/images/gallery/gallery_25.jpg",
    "thumbnailUrl": "/images/gallery/gallery_25.jpg",
    "originalUrl": "https://i.ibb.co/Xk5wFQ3k/IMG-20251212-202918.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 25,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:31.598Z",
    "updatedAt": "2026-08-19T11:35:31.598Z"
  },
  {
    "id": "b68d3fde-194a-4a11-8461-bf31ad3350da",
    "title": "Live Caricature",
    "slug": "live-caricature-26",
    "imageUrl": "/images/gallery/gallery_26.jpg",
    "thumbnailUrl": "/images/gallery/gallery_26.jpg",
    "originalUrl": "https://i.ibb.co/GGTtyk2/IMG-20251211-195429.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 26,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:31.922Z",
    "updatedAt": "2026-08-19T11:35:31.922Z"
  },
  {
    "id": "957f8824-ee9b-47a7-b641-ae8817fbc319",
    "title": "Caricature commissioned work",
    "slug": "caricature-commissioned-work-27",
    "imageUrl": "/images/gallery/gallery_27.jpg",
    "thumbnailUrl": "/images/gallery/gallery_27.jpg",
    "originalUrl": "https://i.ibb.co/pjHn3bZc/IMG-20251211-194811.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 27,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:32.133Z",
    "updatedAt": "2026-08-19T11:35:32.133Z"
  },
  {
    "id": "806c50b6-400a-4617-abbb-f5998dd409ea",
    "title": "Caricature Commission work",
    "slug": "caricature-commission-work-28",
    "imageUrl": "/images/gallery/gallery_28.jpg",
    "thumbnailUrl": "/images/gallery/gallery_28.jpg",
    "originalUrl": "https://i.ibb.co/6J1jtf0d/IMG-20251109-174633.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 28,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:32.393Z",
    "updatedAt": "2026-08-19T11:35:32.393Z"
  },
  {
    "id": "8414a2e4-616b-4236-9130-b86db6a75e85",
    "title": "Self Caricature art",
    "slug": "self-caricature-art-29",
    "imageUrl": "/images/gallery/gallery_29.jpg",
    "thumbnailUrl": "/images/gallery/gallery_29.jpg",
    "originalUrl": "https://i.ibb.co/Wrc9CL4/IMG-20251102-122647.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 29,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:32.611Z",
    "updatedAt": "2026-08-19T11:35:32.611Z"
  },
  {
    "id": "ffd3a120-851e-4acb-9239-322535de333b",
    "title": "Live Caricature",
    "slug": "live-caricature-30",
    "imageUrl": "/images/gallery/gallery_30.jpg",
    "thumbnailUrl": "/images/gallery/gallery_30.jpg",
    "originalUrl": "https://i.ibb.co/fz7nTdht/IMG-20251031-235933.jpg",
    "category": "Caricature",
    "description": "",
    "year": "2025",
    "sortOrder": 30,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:32.851Z",
    "updatedAt": "2026-08-19T11:35:32.851Z"
  },
  {
    "id": "ab52f9a7-7e0c-451f-81ad-9f48b26c4efa",
    "title": "Pawan Kalyan",
    "slug": "pawan-kalyan-31",
    "imageUrl": "/images/gallery/gallery_31.jpg",
    "thumbnailUrl": "/images/gallery/gallery_31.jpg",
    "originalUrl": "https://i.ibb.co/7xQ1c010/IMG-20250709-203254.jpg",
    "category": "Pencil Portraits",
    "description": "Pawan Kalyan Pencil Drawing\n\nThis hand-drawn pencil portrait of Pawan Kalyan focuses on capturing his strong personality and distinctive expressions. Careful shading and precise line work bring depth and realism to the portrait.\n\nThe use of graphite tones emphasizes facial structure and character, giving the artwork a powerful and classic look. This piece reflects patience, observation, and technical skill.\n\nMedium: Pencil on paper(Artline pencils on Ivory)\nType: Hand-drawn original artwork",
    "year": "2021",
    "sortOrder": 31,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:33.109Z",
    "updatedAt": "2026-08-19T11:35:33.109Z"
  },
  {
    "id": "6ff1612e-4aef-4977-9d7b-db862b6e8a09",
    "title": "Tortoise",
    "slug": "tortoise-32",
    "imageUrl": "/images/gallery/gallery_32.jpg",
    "thumbnailUrl": "/images/gallery/gallery_32.jpg",
    "originalUrl": "https://i.ibb.co/XxR0m66C/IMG-20250709-160803.jpg",
    "category": "Painting",
    "description": "Multicolour Tortoise Acrylic Painting\n\nThis acrylic painting of a tortoise is created on canvas using a rich mix of bright, contrasting colours. The colourful treatment gives the artwork a lively and eye-catching appearance, turning the tortoise into a bold visual subject.\n\nLayered acrylic strokes and a balanced colour palette create texture and movement, making the painting feel energetic and modern. This piece brings freshness and creativity to any space.\n\nSuitable for contemporary interiors, art studios, cafés, or creative displays, this artwork adds a strong splash of colour and character.\n\nMedium: Acrylic on canvas\nType: Hand-painted original artwork",
    "year": "2025",
    "sortOrder": 32,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:33.393Z",
    "updatedAt": "2026-08-19T11:35:33.393Z"
  },
  {
    "id": "de6f28c8-b980-442c-b367-543bea4dba18",
    "title": "Live wedding painting at Hyderabad",
    "slug": "live-wedding-painting-at-hyderabad-33",
    "imageUrl": "/images/gallery/gallery_33.jpg",
    "thumbnailUrl": "/images/gallery/gallery_33.jpg",
    "originalUrl": "https://i.ibb.co/cXKR1yjj/IMG-20251225-165654.jpg",
    "category": "Live Wedding Painting",
    "description": "Live Wedding Painting – Hyderabad\n\nThis artwork is a live wedding painting created at a wedding event in Hyderabad, capturing the couple and the atmosphere as the celebration took place. The painting was completed on-site within 5 hours, reflecting quick observation and confident execution.\n\nThe composition focuses on the emotions, details, and special moments of the occasion, turning a real-time celebration into a lasting visual memory. This piece stands as a unique and personal wedding keepsake.\n\nArtwork Type: Live wedding painting\nLocation: Hyderabad\nCompletion Time: 5 hours",
    "year": "2025",
    "sortOrder": 33,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:33.662Z",
    "updatedAt": "2026-08-19T11:35:33.662Z"
  },
  {
    "id": "8b03a282-d41a-44fc-8ed3-91fff4a34197",
    "title": "Commission work",
    "slug": "commission-work-34",
    "imageUrl": "/images/gallery/gallery_34.jpg",
    "thumbnailUrl": "/images/gallery/gallery_34.jpg",
    "originalUrl": "https://i.ibb.co/FLsZpKNs/IMG-20251106-105438.jpg",
    "category": "Pencil Portraits",
    "description": "Realistic Couple Colour Pencil Artwork (Commissioned)\n\nThis commissioned colour pencil portrait of a couple is created with a strong focus on realism and likeness. Careful colour layering and detailed shading bring natural skin tones, expressions, and emotions to life.\n\nThe artwork is designed to reflect the bond and connection between the couple, making it a meaningful and personal piece. Attention to detail and a refined finish give the portrait a timeless and elegant appearance.\n\nMedium: Colour pencil on paper\nArtwork Type: Commissioned artwork",
    "year": "2025",
    "sortOrder": 34,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:33.960Z",
    "updatedAt": "2026-08-19T11:35:33.960Z"
  },
  {
    "id": "c915d02f-6565-44de-a039-0b6f2213cec8",
    "title": "Avengers",
    "slug": "avengers-35",
    "imageUrl": "/images/gallery/gallery_35.jpg",
    "thumbnailUrl": "/images/gallery/gallery_35.jpg",
    "originalUrl": "https://i.ibb.co/N2MvrnTc/IMG-20250709-133808.jpg",
    "category": "Pencil Portraits",
    "description": "Avengers Colour Pencil Drawing\n\nThis colour pencil drawing inspired by the Avengers brings together iconic superheroes in a dynamic and powerful composition. Detailed pencil work and bold colour layering highlight each character’s individuality while maintaining balance within the group scene.\n\nThe artwork captures action, unity, and heroic energy through expressive features and strong contrasts. Created with patience and precision, this piece reflects dedication to character design and comic-inspired illustration.\n\nIdeal for fans of superhero art, collectors, or modern interior displays, this drawing stands out with its vibrant presence.\n\nMedium: Colour pencil on paper(Camlin premium triangular colour pencils on sketch book)\nType: Hand-drawn original artwork",
    "year": "2023",
    "sortOrder": 35,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:34.329Z",
    "updatedAt": "2026-08-19T11:35:34.329Z"
  },
  {
    "id": "946b64ea-13c9-41d5-9788-455fd366032c",
    "title": "Sri Krishna",
    "slug": "sri-krishna-36",
    "imageUrl": "/images/gallery/gallery_36.jpg",
    "thumbnailUrl": "/images/gallery/gallery_36.jpg",
    "originalUrl": "https://i.ibb.co/NgCGqyk7/IMG-20220117-174708.jpg",
    "category": "Pencil Portraits",
    "description": "Krishna Colour Pencil Artwork with Lotus and Flute\n\nThis detailed colour pencil illustration of Lord Krishna presents him in a calm and graceful form, with a lotus ,flute and peacock feather completing his divine identity. Subtle colour transitions and precise pencil work create a soft yet vibrant visual effect.\n\nEach element in the artwork symbolizes purity, harmony, and spiritual depth. The balanced composition and gentle expressions evoke a sense of peace and devotion, making this piece visually soothing and emotionally uplifting.\n\nWell suited for sacred spaces, artistic displays, or spiritual collections, this artwork reflects dedication, patience, and refined craftsmanship.\n\nMedium: Colour pencil on paper(Camlin premium triangular colour pencils on Ivory paper)\nType: Original hand-drawn artwork",
    "year": "2022",
    "sortOrder": 36,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:34.661Z",
    "updatedAt": "2026-08-19T11:35:34.661Z"
  },
  {
    "id": "73cf9f14-00db-4ea3-81e4-21fa7054b401",
    "title": "Lord Krishna",
    "slug": "lord-krishna-37",
    "imageUrl": "/images/gallery/gallery_37.jpg",
    "thumbnailUrl": "/images/gallery/gallery_37.jpg",
    "originalUrl": "https://i.ibb.co/9k8TSGq4/IMG-20250925-194521.png",
    "category": "Pencil Portraits",
    "description": "Cute Krishna Pencil Artwork\n\nThis hand-drawn pencil illustration of Lord Krishna captures his playful and charming personality. Soft shading and delicate pencil strokes bring out his joyful expressions, youthful features, and iconic elements like  peacock feather.\n\nThe artwork radiates innocence, warmth, and devotion, making it a perfect piece for home décor, kids’ rooms, or personal collections.\n\nMedium: Pencil on paper(Doms pencils on 70gsm a4 paper)\nType: Hand-drawn original artwork",
    "year": "2025",
    "sortOrder": 37,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:35.037Z",
    "updatedAt": "2026-08-19T11:35:35.037Z"
  },
  {
    "id": "366182e7-4005-4447-9d51-91418379ee6c",
    "title": "Son Goku",
    "slug": "son-goku-38",
    "imageUrl": "/images/gallery/gallery_38.jpg",
    "thumbnailUrl": "/images/gallery/gallery_38.jpg",
    "originalUrl": "https://i.ibb.co/XxYPjrsC/IMG-20250709-224957.jpg",
    "category": "Pencil Portraits",
    "description": "Son Goku – Dragon Ball Colour Pencil Artwork\n\nThis hand-drawn colour pencil artwork of Son Goku from Dragon Ball captures his iconic energy and determined expression. Vibrant colours and detailed pencil layering bring the character to life, emphasizing his dynamic personality and heroic presence.\n\nThe artwork focuses on precision, motion, and character essence, reflecting both skill and passion for anime illustration. A perfect piece for anime fans, collectors, or art enthusiasts.\n\nMedium: Colour pencil on paper(Brustro pencils and paper)\nType: Original hand-drawn artwork",
    "year": "2024",
    "sortOrder": 38,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:35.323Z",
    "updatedAt": "2026-08-19T11:35:35.323Z"
  },
  {
    "id": "af8f3d1d-1250-4b37-ba0e-d7f7208bfe63",
    "title": "Live wedding Painting at Wanaparthy ",
    "slug": "live-wedding-painting-at-wanaparthy-39",
    "imageUrl": "/images/gallery/gallery_39.jpg",
    "thumbnailUrl": "/images/gallery/gallery_39.jpg",
    "originalUrl": "https://i.ibb.co/BVr1DTWX/IMG-20251225-163551.jpg",
    "category": "Live Wedding Painting",
    "description": "This artwork is a live wedding painting created on the couple’s special day in Wanaparthy. The scene was painted directly at the venue, capturing the emotions, attire, and atmosphere of the wedding as it unfolded.\n\nCompleted within 6 hours, this acrylic painting on canvas reflects quick observation, confident brushwork, and the ability to translate real moments into a lasting visual memory. The composition focuses on the bond between the couple and the joy of the occasion.\n\nThis piece stands as a one-of-a-kind wedding keepsake, preserving the celebration in a timeless artistic form.\n\nMedium: Acrylic on canvas\nArtwork Type: Live wedding painting\nLocation: Wanaparthy\nDuration: Completed in 6 hours",
    "year": "2025",
    "sortOrder": 39,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:35.638Z",
    "updatedAt": "2026-08-19T11:35:35.639Z"
  },
  {
    "id": "945f837d-b164-4070-a2d5-ddde594855a4",
    "title": "Couple Colour Pencil Portrait",
    "slug": "couple-colour-pencil-portrait-40",
    "imageUrl": "/images/gallery/gallery_40.jpg",
    "thumbnailUrl": "/images/gallery/gallery_40.jpg",
    "originalUrl": "https://i.ibb.co/67Gs9JB3/IMG-20251225-162658.jpg",
    "category": "Pencil Portraits",
    "description": "Couple Portrait with Colour Pencils\n\nThis hand-rendered colour pencil illustration of a couple is created with close attention to facial features, skin tones, and subtle expressions. Layered pencil strokes and controlled blending bring clarity, softness, and depth to the image.\n\nThe artwork highlights companionship and shared emotion through natural poses and balanced composition. Crafted with care, this portrait serves as a lasting visual memory and a personal piece of fine art.\n\nMedium: Colour pencils on paper(Brustro colour pencil and Ivory paper)\nType: Hand-drawn original artwork",
    "year": "2023",
    "sortOrder": 40,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:35.987Z",
    "updatedAt": "2026-08-19T11:35:35.987Z"
  },
  {
    "id": "c5aaa6bd-9d35-466f-a509-912702a1d23b",
    "title": "Prabhas",
    "slug": "prabhas-41",
    "imageUrl": "/images/gallery/gallery_41.jpg",
    "thumbnailUrl": "/images/gallery/gallery_41.jpg",
    "originalUrl": "https://i.ibb.co/QjT3Zzjn/IMG-20251225-162914.jpg",
    "category": "Pencil Portraits",
    "description": "Prabhas – Kalki Movie Colour Pencil Artwork\n\nThis colour pencil artwork inspired by Prabhas from the movie Kalki is carefully drawn with attention to facial details, expressions, and colour balance. Fine pencil work and smooth shading bring realism and depth to the portrait.\n\nThe artwork captures the powerful presence and character styling from the film, reflecting both artistic skill and dedication to detail. This piece showcases precision, patience, and a strong understanding of portrait art.\n\nMedium: Colour pencil on paper\nType: Hand-drawn original artwork",
    "year": "2024",
    "sortOrder": 41,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:36.299Z",
    "updatedAt": "2026-08-19T11:35:36.299Z"
  },
  {
    "id": "21bbcf74-a21b-4df6-8933-8bba6268ca06",
    "title": "Radha Krishna",
    "slug": "radha-krishna-42",
    "imageUrl": "/images/gallery/gallery_42.jpg",
    "thumbnailUrl": "/images/gallery/gallery_42.jpg",
    "originalUrl": "https://i.ibb.co/Jjcs6ppF/IMG-20251225-163136.jpg",
    "category": "Painting",
    "description": "Radha Krishna Watercolour Painting\n\nThis original watercolour painting of Radha Krishna with Gomatha (the sacred cow) is created with soft colours and gentle brushwork. The flowing watercolour tones bring a peaceful and devotional mood to the artwork.\n\nRadha and Krishna symbolize love, harmony, and divine connection, while Gomatha represents purity, care, and abundance. Together, they create a spiritually meaningful and calming composition.\n\nIdeal for home décor, prayer rooms, meditation spaces, or spiritual collections, this painting reflects devotion and traditional artistic beauty.\n\nMedium: Watercolour on paper(camlin watercolours)\nType: Hand-painted original artwork",
    "year": "2022",
    "sortOrder": 42,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:36.558Z",
    "updatedAt": "2026-08-19T11:35:36.558Z"
  },
  {
    "id": "eb269934-a9d2-4543-aa6b-e0b96517ecb4",
    "title": "Satoru Gojo",
    "slug": "satoru-gojo-43",
    "imageUrl": "/images/gallery/gallery_43.jpg",
    "thumbnailUrl": "/images/gallery/gallery_43.jpg",
    "originalUrl": "https://i.ibb.co/23f8Msmr/IMG-20251211-194007.jpg",
    "category": "Pencil Portraits",
    "description": "Gojo Anime Commissioned Artwork\n\nThis commissioned colour pencil artwork of Gojo, inspired by Jujutsu Kaisen, is created on paper with careful attention to detail. Smooth colour blending and precise pencil work highlight the character’s expression, features, and iconic style. \nDesigned according to the client’s requirements, this artwork reflects creativity, accuracy, and attention to details.\n\nMedium: Colour pencil on paper(Brustro colour pencils and paper)\nType: Commissioned anime artwork",
    "year": "2023",
    "sortOrder": 43,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:36.809Z",
    "updatedAt": "2026-08-19T11:35:36.809Z"
  },
  {
    "id": "151c4547-eca8-4a21-9bd9-58353248dd55",
    "title": "Monkey D.Luffy",
    "slug": "monkey-d-luffy-44",
    "imageUrl": "/images/gallery/gallery_44.jpg",
    "thumbnailUrl": "/images/gallery/gallery_44.jpg",
    "originalUrl": "https://i.ibb.co/DftSsJWF/IMG-20250808-124558.jpg",
    "category": "Pencil Portraits",
    "description": "Luffy Anime Colour Pencil Artwork\n\nThis colour pencil artwork of Luffy, inspired by One Piece, combines anime illustration with an Indian traditional fanart approach. The artwork focuses on expressive detailing, strong character features, and smooth colour blending to bring Luffy’s personality to life.\n\nThis artwork received First Prize in the Indian Traditional Anime Fanart Contest conducted by the Rotaract Club of St. Peter’s Engineering College, where I am currently studying. The award reflects creativity, originality, and artistic skill.\n\nMedium: Colour pencil on paper(camlin premium triangular colour pencils on ivory papar)\nAchievement: First Prize – Indian Traditional Anime Fanart Contest",
    "year": "2024",
    "sortOrder": 44,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:37.067Z",
    "updatedAt": "2026-08-19T11:35:37.067Z"
  },
  {
    "id": "c0708fbc-7a99-4935-8f08-ea609a68774d",
    "title": "Skull",
    "slug": "skull-45",
    "imageUrl": "/images/gallery/gallery_45.jpg",
    "thumbnailUrl": "/images/gallery/gallery_45.jpg",
    "originalUrl": "https://i.ibb.co/7t3xKB3b/IMG-20251211-193823.jpg",
    "category": "Pencil Portraits",
    "description": "Realistic Metallic Skull Pencil Drawing\n\nThis original pencil drawing of a skull is created on paper with detailed shading to achieve a realistic metallic finish. Careful use of light and shadow gives the skull a strong, reflective metal-like appearance while maintaining accurate structure and depth.\n\nThe monochrome pencil work highlights texture, form, and contrast, resulting in a bold and striking artwork. This piece reflects technical skill and attention to realism.\n\nIdeal for art collections, studios, or modern interiors, this drawing has a powerful and dramatic presence.\n\nMedium: Pencil on paper(Steadler Pencils on Ivory)\nType: Hand-drawn original artwork",
    "year": "2025",
    "sortOrder": 45,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:37.269Z",
    "updatedAt": "2026-08-19T11:35:37.269Z"
  },
  {
    "id": "77490f56-5f9e-494b-83df-0c5eb826a7f9",
    "title": "Rose",
    "slug": "rose-46",
    "imageUrl": "/images/gallery/gallery_46.jpg",
    "thumbnailUrl": "/images/gallery/gallery_46.jpg",
    "originalUrl": "https://i.ibb.co/3mqHvW3D/IMG-20240608-220020.jpg",
    "category": "Pencil Portraits",
    "description": "Realistic Rose Graphite Pencil Artwork\n\nThis original graphite pencil drawing of a rose is created on paper with fine detailing and smooth shading to achieve a realistic look. Careful pencil work highlights the delicate petals, natural curves, and soft textures of the flower.\n\nThe monochrome tones add elegance and depth, making the artwork calm and timeless. This piece reflects patience, precision, and an appreciation for natural beauty.\n\nIdeal for art collections, home decor, or portfolios, this realistic rose drawing has a classic and refined appeal.\n\nMedium: Graphite pencil on paper(Steadler pencils on classmate sketch book)\nType: Hand-drawn original artwork",
    "year": "2024",
    "sortOrder": 46,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:37.569Z",
    "updatedAt": "2026-08-19T11:35:37.569Z"
  },
  {
    "id": "ddc3b1b2-80d4-4356-91ab-a02fc8c1cb33",
    "title": "graphite pencil portrait",
    "slug": "graphite-pencil-portrait-47",
    "imageUrl": "/images/gallery/gallery_47.jpg",
    "thumbnailUrl": "/images/gallery/gallery_47.jpg",
    "originalUrl": "https://i.ibb.co/600jb8tc/IMG-20210910-103605.jpg",
    "category": "Pencil Portraits",
    "description": "This original hand-drawn pencil portrait captures the likeness and personality of my brother with careful attention to detail. Fine shading and precise line work are used to create depth, expression, and a realistic finish.\n\nCreated with patience and skill, this portrait reflects emotion, character, and craftsmanship. It is a timeless piece that preserves a personal moment in a classic artistic form.\n\nMedium: Pencil on paper(Art Line Pencils on Ivory paper)\nType: Hand-drawn portrait artwork",
    "year": "2021",
    "sortOrder": 47,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:37.815Z",
    "updatedAt": "2026-08-19T11:35:37.815Z"
  },
  {
    "id": "823f73bf-9dd0-4385-8b20-5baaa21e0e00",
    "title": "Puppy",
    "slug": "puppy-48",
    "imageUrl": "/images/gallery/gallery_48.jpg",
    "thumbnailUrl": "/images/gallery/gallery_48.jpg",
    "originalUrl": "https://i.ibb.co/gMCj5030/IMG-20250808-124406.jpg",
    "category": "Painting",
    "description": "Cute Puppy Acrylic Painting\n\nThis original acrylic pop art painting of a cute puppy is created on canvas using bold colours and playful contrasts. The pop art style gives the artwork a lively and modern look, while expressive details capture the puppy’s charm and joyful personality.\n\nPainted with high-quality acrylics, this artwork adds brightness and fun to any space. It is perfect for modern interiors, kids’ rooms, studios, cafés, or as a cheerful gift.\n\nMedium: Acrylic on canvas\nType: Hand-painted original artwork",
    "year": "2025",
    "sortOrder": 48,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:38.136Z",
    "updatedAt": "2026-08-19T11:35:38.136Z"
  },
  {
    "id": "5dac152f-8cd3-4718-8ada-ab528c96186c",
    "title": "Sri Ram",
    "slug": "sri-ram-49",
    "imageUrl": "/images/gallery/gallery_49.jpg",
    "thumbnailUrl": "/images/gallery/gallery_49.jpg",
    "originalUrl": "https://i.ibb.co/Q3r9pWL0/IMG-20251211-194452.jpg",
    "category": "Pencil Portraits",
    "description": "Lord Ram Colour Pencil Artwork\n\nThis original colour pencil artwork of Lord Ram at the age of 21 captures his youthful strength, calm expression, and divine grace. Fine pencil detailing and soft colour blending bring depth and clarity to the portrait, highlighting purity, discipline, and inner strength.\n\nLord Ram represents righteousness, courage, and moral values. The gentle yet precise use of colour pencils gives the artwork a refined and timeless appearance.\n\nIdeal for home décor, prayer spaces, offices, or spiritual collections, this artwork reflects devotion, patience, and skilled craftsmanship.\n\nMedium: Colour pencil on paper(premium triangular colour pencils,ivory paper 210gsm)\nType: Hand-drawn original artwork",
    "year": "2023",
    "sortOrder": 49,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:38.448Z",
    "updatedAt": "2026-08-19T11:35:38.448Z"
  },
  {
    "id": "c32f76b5-1d56-4b8a-bd79-f02621f5dc44",
    "title": "Lord Ganesha",
    "slug": "lord-ganesha-50",
    "imageUrl": "/images/gallery/gallery_50.jpg",
    "thumbnailUrl": "/images/gallery/gallery_50.jpg",
    "originalUrl": "https://i.ibb.co/9Qs28ND/IMG-20251225-152109.jpg",
    "category": "Painting",
    "description": "Watercolour Ganesha Painting on Wood\n\nThis is an original hand-painted watercolour artwork of Lord Ganesha on wood. Soft watercolour tones are used to create a calm and graceful look, while the natural wood surface adds warmth and character to the painting.\n\nLord Ganesha represents wisdom, positivity, and the removal of obstacles. The gentle colours and fine details make this artwork suitable for both modern and traditional spaces.\n\nIdeal for home décor, prayer rooms, offices, or as a thoughtful gift, this painting brings a peaceful and uplifting presence to any environment.\n\nMedium: Watercolour on wood\nType: Original hand-painted artwork",
    "year": "2022",
    "sortOrder": 50,
    "isFeatured": false,
    "createdAt": "2026-08-19T11:35:38.714Z",
    "updatedAt": "2026-08-19T11:35:38.714Z"
  }
];
